const fs=require('fs'),vm=require('vm'),crypto=require('crypto'),path=require('path');
const sandbox={console,crypto,Buffer,process,require,setTimeout,clearTimeout,URL,URLSearchParams};sandbox.globalThis=sandbox;
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'runtime-prelude.js'),'utf8'),sandbox,{filename:'runtime-prelude.js'});
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'Code.gs'),'utf8'),sandbox,{filename:'Code.gs'});
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'security-overrides.js'),'utf8'),sandbox,{filename:'security-overrides.js'});
const PUBLIC_ACTIONS=new Set([
'activateCustomerLicenseFromUi','addProduct','approveReplacementLicenseKeyFromMaster','authorizeSupportCustomerSessionFromMaster','changeManagedPin','changeManagedUsername','configureDatabaseFromUi','convertTrialToRegularFromMaster','createManagedAccount','createMasterSupportMember','createShopLinkFromMaster','decideFeaturePermissionRequest','decideLicensePaymentProofFromMaster','decidePaymentSetupRequest','deleteGlobalCustomerLicensePriceFromMaster','deleteRestaurantMenuItem','deleteShopLinkFromMaster','enableMasterSupportAccess','generateLicenseKeyForTierFromMaster','generateShopActivationKeyForMaster','getAccessManagement','getBankFinanceLedger','getCustomerBranches','getCustomerLicenseOffers','getCustomers','getDatabaseSetupStatus','getGlobalCustomerLicensePrices','getHistoryRecordForPrint','getInitialData','getInvoiceStockProducts','getMasterShopDashboard','getRestaurantMenu','getShanOwnerOperations','getSoftwareUpdateNotice','getStockLookupProducts','getStockLookupProducts','getSuppliers','importSimpleInvoiceBackup','inspectPosBackup','inspectSimpleInvoiceBackup','listAllCustomerRequestMessages','listBillHistory','listFeaturePermissionRequests','listLicensePaymentProofsFromMaster','listPaymentSetupRequests','listReplacementKeyRequestsFromMaster','loginWithPin','loginWithSupportSession','logoutLoginSession','manageInternalBankFinance','managePaymentOption','requestCustomerBranchCreation','requestCustomerLicensePurchase','requestReplacementLicenseKeyFromCustomer','restorePosBackup','restoreSimpleInvoiceStock','saveBankLedgerTransaction','saveBill','saveCctvApplication','saveCompanyDetails','saveCustomer','saveCustomerBranch','saveFinanceAsset','saveInvoiceStockPurchase','saveJobNote','saveLoan','saveMobileServiceApplication','savePayment','saveRestaurantMenuItem','saveShanOwnerBranch','saveShanOwnerStaff','saveShanOwnerTask','saveShanPosSystemManagement','saveSoftwareUpdateNotice','saveSoftwareUpdateNotice','saveSupplier','setBranchExpansionApprovalFromMaster','setCustomerLicensePriceFromMaster','setGlobalCustomerLicensePriceFromMaster','setShopLicenseDaysFromMaster','setShopLinkActiveFromMaster','setShopLinkSuspendedFromMaster','submitCustomerLicensePaymentProof','undoLastPosRestore','updateCustomerFirstLoginFromMaster','updateManagedAccountPermissions','updateMyProfile','updateProductBarcode','updateShopActivationKeyFromMaster','updateShopPermissionsFromMaster'
]);
['submitCustomerSupportRequest','listMasterNotifications','listSupportNotifications'].forEach(action=>PUBLIC_ACTIONS.add(action));
const ANONYMOUS_ACTIONS=new Set(['loginWithPin','getDatabaseSetupStatus','bootstrapMasterOwner']);
const headers={'content-type':'application/json','cache-control':'no-store'};
exports.handler=async event=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:{'access-control-allow-headers':'Content-Type, Authorization'},body:''};try{const x=JSON.parse(event.body||'{}'),action=String(x.action||''),payload=x.payload||{};if(!PUBLIC_ACTIONS.has(action)&&action!=='bootstrapMasterOwner')throw new Error('Unsupported API action.');sandbox.RUNTIME.requestId=event.headers?.['x-nf-request-id']||crypto.randomUUID();sandbox.RUNTIME.shop=String(payload&&payload.shopCode||'').toUpperCase();const fn=sandbox[action];if(typeof fn!=='function')throw new Error('Unsupported API action.');let account=null;if(!ANONYMOUS_ACTIONS.has(action)){if(payload&&typeof payload==='object'&&typeof sandbox.setShopContextFromRequest_==='function')sandbox.setShopContextFromRequest_(payload);const token=(payload&&typeof payload==='object')?(payload.actorPin||payload.token||payload.pin):payload;account=sandbox.accountForPin_(token);if(!account)throw Object.assign(new Error('Please log in again.'),{statusCode:401});}const data=await Promise.resolve(fn(payload));if(account&&typeof sandbox.recordCustomerRequest_==='function')sandbox.recordCustomerRequest_(account,action);if(account&&typeof sandbox.recordSupportOperation_==='function')sandbox.recordSupportOperation_(account,action);return{statusCode:200,headers,body:JSON.stringify({ok:true,data})}}catch(e){console.error(e);return{statusCode:e.statusCode||400,headers,body:JSON.stringify({ok:false,error:e.message||String(e)})}}};
