'use strict';
const crypto=require('crypto'),{execFileSync}=require('child_process'),AdmZip=require('adm-zip');
function env_(n){const v=process.env[n];if(!v)throw new Error('Missing Netlify environment variable: '+n);return v}
const RUNTIME={requestId:'',shop:''};globalThis.RUNTIME=RUNTIME;
function dbReq(method,table,query,body){const base=env_('SUPABASE_URL').replace(/\/$/,'')+'/rest/v1/'+table;const url=base+(query?'?'+query:'');const args=['-sS','-f','-X',method,url,'-H','apikey: '+env_('SUPABASE_SERVICE_ROLE_KEY'),'-H','Authorization: Bearer '+env_('SUPABASE_SERVICE_ROLE_KEY'),'-H','Content-Type: application/json','-H','Prefer: resolution=merge-duplicates,return=representation'];if(body!==undefined)args.push('--data-binary',JSON.stringify(body));try{const out=execFileSync('curl',args,{encoding:'utf8',maxBuffer:60*1024*1024});return out?JSON.parse(out):[]}catch(e){throw new Error((e.stderr||e.message||String(e)).trim())}}
function propRead(){const rows=dbReq('GET','app_kv','select=key,value');const out={};(rows||[]).forEach(r=>out[r.key]=r.value);return out}
const AppProperties={getScriptProperties:()=>({getProperty:k=>propRead()[k]??null,setProperty:(k,v)=>{dbReq('POST','app_kv','on_conflict=key',[{key:k,value:String(v),updated_at:new Date().toISOString()}]);return this},deleteProperty:k=>{dbReq('DELETE','app_kv','key=eq.'+encodeURIComponent(k));return this},getProperties:()=>propRead(),setProperties:o=>{Object.keys(o||{}).forEach(k=>dbReq('POST','app_kv','on_conflict=key',[{key:k,value:String(o[k]),updated_at:new Date().toISOString()}]));return this}})};
const AppCache={getScriptCache:()=>({get:k=>{const r=dbReq('GET','app_cache','key=eq.'+encodeURIComponent(k)+'&select=value,expires_at');if(!r.length)return null;if(r[0].expires_at&&new Date(r[0].expires_at)<=new Date()){dbReq('DELETE','app_cache','key=eq.'+encodeURIComponent(k));return null}return r[0].value},put:(k,v,t)=>{dbReq('POST','app_cache','on_conflict=key',[{key:k,value:String(v),expires_at:new Date(Date.now()+Number(t||600)*1000).toISOString(),updated_at:new Date().toISOString()}]);return this},remove:k=>{dbReq('DELETE','app_cache','key=eq.'+encodeURIComponent(k));return this}})};
const AppSession={getTemporaryActiveUserKey:()=>RUNTIME.requestId||'anonymous',getScriptTimeZone:()=>'Asia/Colombo'};
const AppLock={getScriptLock:()=>({waitLock:()=>true,tryLock:()=>true,releaseLock:()=>{}})};
const RuntimeApp={getScriptId:()=>process.env.NETLIFY_SITE_ID||'shan-pos',getService:()=>({getUrl:()=>process.env.URL||process.env.DEPLOY_PRIME_URL||''}),getOAuthToken:()=>'',getProjectTriggers:()=>[],newTrigger:()=>({timeBased:()=>({everyDays:()=>({atHour:()=>({inTimezone:()=>({create:()=>{}})})}),onMonthDay:()=>({atHour:()=>({inTimezone:()=>({create:()=>{}})})})})})};
const AppHtml={createHtmlOutput:()=>({setTitle:()=>({}),}),createTemplateFromFile:()=>({evaluate:()=>({setTitle:()=>({addMetaTag:()=>({})})})})};
const HttpClient={};
class CompatBlob{constructor(bytes,mime,name){this.bytes=Buffer.from(bytes||[]);this.mime=mime||'application/octet-stream';this.name=name||'file'}getBytes(){return this.bytes}getBlob(){return this}getContentType(){return this.mime}getName(){return this.name}}
const AppUtilities={Charset:{UTF_8:'UTF-8'},DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(a,v)=>Array.from(crypto.createHash('sha256').update(String(v)).digest()),base64Encode:v=>Buffer.from(v instanceof Uint8Array?v:String(v)).toString('base64'),base64Decode:v=>Buffer.from(String(v),'base64'),getUuid:()=>crypto.randomUUID(),newBlob:(b,m,n)=>new CompatBlob(b,m,n),zip:(bs,n)=>{const z=new AdmZip();(bs||[]).forEach(b=>z.addFile(b.getName(),b.getBytes()));return new CompatBlob(z.toBuffer(),'application/zip',n||'archive.zip')},unzip:b=>{const z=new AdmZip(b.getBytes());return z.getEntries().map(e=>new CompatBlob(e.getData(),'application/octet-stream',e.entryName))} ,formatDate:(d,t,f)=>{const x=new Date(d),p=n=>String(n).padStart(2,'0');return String(f||'yyyy-MM-dd').replace('yyyy',x.getFullYear()).replace('MM',p(x.getMonth()+1)).replace('dd',p(x.getDate())).replace('HH',p(x.getHours())).replace('mm',p(x.getMinutes())).replace('ss',p(x.getSeconds()))}};
const StorageApp={createFile:b=>{const id='file-'+crypto.randomUUID();dbReq('POST','app_files','on_conflict=id',[{id,name:b.getName(),mime:b.getContentType(),bytes:b.getBytes().toString('base64'),folder_id:'root',trashed:false}]);return{getId:()=>id,getBlob:()=>b,getUrl:()=>((process.env.URL||'')+'/.netlify/functions/file?id='+encodeURIComponent(id)),setTrashed:v=>dbReq('PATCH','app_files','id=eq.'+encodeURIComponent(id),{trashed:true})}},getFileById:id=>{const r=dbReq('GET','app_files','id=eq.'+encodeURIComponent(id)+'&select=name,mime,bytes,trashed');if(!r.length||r[0].trashed)throw new Error('File not found.');const b=new CompatBlob(Buffer.from(r[0].bytes,'base64'),r[0].mime,r[0].name);return{getId:()=>id,getBlob:()=>b,setTrashed:()=>dbReq('PATCH','app_files','id=eq.'+encodeURIComponent(id),{trashed:true})}},getRootFolder:()=>({getFoldersByName:()=>({hasNext:()=>false}),createFolder:()=>({createFile:b=>StorageApp.createFile(b)})}),getFolderById:()=>({createFile:b=>StorageApp.createFile(b),getFoldersByName:()=>({hasNext:()=>false})})};
const AppMail={sendEmail:()=>true};
const DataSheetApp={openById:()=>{throw new Error('Direct external spreadsheet access is not available in the Netlify/Supabase build.')}};
